# -*- coding: utf-8 -*-
"""Data Visualization Assignment 3.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yk-vCPMSmJoaQe1qPyS0u8nfIGhEgNEp
"""

import pandas as pd

train = pd.read_csv("train.csv")

train.head()

train["datetime"]=pd.to_datetime(train["datetime"])
train.head()

#data type of each column
train.info()

#no. of rows
print("Rows", len(train))

#Missing values
print("Missing Values", train.isna().sum())

#Year
train["year"]= train["datetime"].dt.year

#Month
train["month"]=train["datetime"].dt.month

#Day
train["weekday"]=train["datetime"].dt.day_name()

#Hour
train["hour"]=train["datetime"].dt.hour

train.head()

#Season Mapping
season_map={1: "Spring", 2: "Summer", 3:"Fall", 4: "Winter"}
train['season']=train['season'].map(season_map)

train.head()

#Summing up casual and registered bikes
train.groupby("year")[["casual","registered"]].sum()

#mean of the hourly total rentals count by season

season_mean=train.groupby("season")["count"].mean()
print(season_mean)
print("\nHighest", season_mean.idxmax())

# Create working day analysis
working_analysis = train.groupby(['workingday', 'year'])[['registered', 'casual']].mean()

print("Mean rentals by working day and year:")
print(working_analysis)

registered_comparison = train.groupby('workingday')['registered'].mean()
print(f"\nRegistered users - Working days: {registered_comparison[1]:.1f}")
print(f"Registered users - Non-working days: {registered_comparison[0]:.1f}")

casual_comparison = train.groupby('workingday')['casual'].mean()
print(f"Casual users - Working days: {casual_comparison[1]:.1f}")
print(f"Casual users - Non-working days: {casual_comparison[0]:.1f}")

#Weather analysis

weather_map = {
    1: 'Clear/Cloudy',
    2: 'Mist/Cloudy',
    3: 'Light Rain/Snow',
    4: 'Heavy Rain/Storm'
}
train['weather_desc'] = train['weather'].map(weather_map)

weather_means = train.groupby('weather')['count'].mean()
weather_means_desc = train.groupby('weather_desc')['count'].mean()

print("Weather vs Average Hourly Rentals:")
print(weather_means_desc.sort_values(ascending=False))

print(f"\nHighest: {weather_means_desc.idxmax()} ({weather_means_desc.max():.1f})")
print(f"Lowest: {weather_means_desc.idxmin()} ({weather_means_desc.min():.1f})")

#Correlation analysis
numerical_cols = ['temp', 'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count']

correlation_matrix = train[numerical_cols].corr()

count_correlations = correlation_matrix['count'].sort_values(ascending=False)
print("Correlations with Total Rentals (count):")
print(count_correlations)

print(f"\nHighest correlation: {count_correlations.index[1]} (r = {count_correlations.iloc[1]:.3f})")

#Create day_period column

def create_day_period(hour):
    if 0 <= hour <= 6:
        return 'night'
    elif 6 < hour <= 12:
        return 'morning'
    elif 12 < hour <= 18:  # Fixed: was 12-6 (should be 12-18)
        return 'afternoon'
    else:  # 18-24
        return 'evening'

train['day_period'] = train['hour'].apply(create_day_period)

print("Day period distribution:")
print(train['day_period'].value_counts().sort_index())

#Pivot table for day_period vs workingday

pivot_table = train.pivot_table(
    values='count',
    index='day_period',
    columns='workingday',
    aggfunc='mean'
).round(1)

print("Mean Hourly Rentals by Day Period and Working Day:")
print(pivot_table)

# Add labels for better readability
pivot_table.columns = ['Non-Working', 'Working']
print("\nFormatted:")
print(pivot_table)

import pandas as pd
train = pd.read_csv("train.csv")
train.head()
train["datetime"]=pd.to_datetime(train["datetime"])
train.head()
#data type of each column
train.info()
#no. of rows
print("Rows", len(train))
#Missing values
print("Missing Values", train.isna().sum())
#Year
train["year"]= train["datetime"].dt.year
#Month
train["month"]=train["datetime"].dt.month
#Day
train["weekday"]=train["datetime"].dt.day_name()
#Hour
train["hour"]=train["datetime"].dt.hour
train.head()
#Season Mapping
season_map={1: "Spring", 2: "Summer", 3:"Fall", 4: "Winter"}
train['season']=train['season'].map(season_map)
train.head()
#Summing up casual and registered bikes
train.groupby("year")[["casual","registered"]].sum()
#mean of the hourly total rentals count by season

season_mean=train.groupby("season")["count"].mean()
print(season_mean)
print("\nHighest", season_mean.idxmax())
# Create working day analysis
working_analysis = train.groupby(['workingday', 'year'])[['registered', 'casual']].mean()

print("Mean rentals by working day and year:")
print(working_analysis)

registered_comparison = train.groupby('workingday')['registered'].mean()
print(f"\nRegistered users - Working days: {registered_comparison[1]:.1f}")
print(f"Registered users - Non-working days: {registered_comparison[0]:.1f}")

casual_comparison = train.groupby('workingday')['casual'].mean()
print(f"Casual users - Working days: {casual_comparison[1]:.1f}")
print(f"Casual users - Non-working days: {casual_comparison[0]:.1f}")
#Weather analysis

weather_map = {
    1: 'Clear/Cloudy',
    2: 'Mist/Cloudy',
    3: 'Light Rain/Snow',
    4: 'Heavy Rain/Storm'
}
train['weather_desc'] = train['weather'].map(weather_map)

weather_means = train.groupby('weather')['count'].mean()
weather_means_desc = train.groupby('weather_desc')['count'].mean()

print("Weather vs Average Hourly Rentals:")
print(weather_means_desc.sort_values(ascending=False))

print(f"\nHighest: {weather_means_desc.idxmax()} ({weather_means_desc.max():.1f})")
print(f"Lowest: {weather_means_desc.idxmin()} ({weather_means_desc.min():.1f})")
#Correlation analysis
numerical_cols = ['temp', 'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count']

correlation_matrix = train[numerical_cols].corr()

count_correlations = correlation_matrix['count'].sort_values(ascending=False)
print("Correlations with Total Rentals (count):")
print(count_correlations)

print(f"\nHighest correlation: {count_correlations.index[1]} (r = {count_correlations.iloc[1]:.3f})")
#Create day_period column

def create_day_period(hour):
    if 0 <= hour <= 6:
        return 'night'
    elif 6 < hour <= 12:
        return 'morning'
    elif 12 < hour <= 18:  # Fixed: was 12-6 (should be 12-18)
        return 'afternoon'
    else:  # 18-24
        return 'evening'

train['day_period'] = train['hour'].apply(create_day_period)

print("Day period distribution:")
print(train['day_period'].value_counts().sort_index())
#Pivot table for day_period vs workingday

pivot_table = train.pivot_table(
    values='count',
    index='day_period',
    columns='workingday',
    aggfunc='mean'
).round(1)

print("Mean Hourly Rentals by Day Period and Working Day:")
print(pivot_table)

# Add labels for better readability
pivot_table.columns = ['Non-Working', 'Working']
print("\nFormatted:")
print(pivot_table)
#Assignment 3.2

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
numerical_cols = ['temp', 'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count']

fig, axes = plt.subplots(3, 3, figsize=(15, 10))
axes = axes.ravel()

for i, col in enumerate(numerical_cols):
    sns.histplot(train[col], kde=True, ax=axes[i])
    axes[i].set_title(f'Distribution of {col}')

plt.tight_layout()
plt.show()
fig, axes = plt.subplots(3, 3, figsize=(15, 10))
axes = axes.ravel()

for i, col in enumerate(numerical_cols):
    sns.boxplot(y=train[col], ax=axes[i])
    axes[i].set_title(f'Box Plot of {col}')

plt.tight_layout()
plt.show()
working_means = train.groupby('workingday')['count'].mean().round(1)
working_means.index = ['Non-Working', 'Working']

plt.figure(figsize=(8, 6))
sns.barplot(x=working_means.index, y=working_means.values)
plt.title('Mean Hourly Rentals: Working vs Non-Working Days')
plt.ylabel('Mean Rentals')
plt.show()
monthly_means = train.groupby('month')['count'].mean()

plt.figure(figsize=(10, 6))
sns.barplot(x=monthly_means.index, y=monthly_means.values)
plt.title('Mean Hourly Rentals by Month (Both Years Combined)')
plt.xlabel('Month')
plt.ylabel('Mean Rentals')
plt.show()
fig, axes = plt.subplots(1, 2, figsize=(15, 6), sharey=True)

# 2011
monthly_2011 = train[train['year'] == 2011].groupby('month')['count'].mean()
sns.barplot(x=monthly_2011.index, y=monthly_2011.values, ax=axes[0])
axes[0].set_title('2011: Mean Hourly Rentals by Month')
axes[0].set_xlabel('Month')
axes[0].set_ylabel('Mean Rentals')

# 2012
monthly_2012 = train[train['year'] == 2012].groupby('month')['count'].mean()
sns.barplot(x=monthly_2012.index, y=monthly_2012.values, ax=axes[1])
axes[1].set_title('2012: Mean Hourly Rentals by Month')
axes[1].set_xlabel('Month')

plt.tight_layout()
plt.show()
hourly_means = train.groupby('hour')['count'].mean()

plt.figure(figsize=(12, 6))
sns.lineplot(x=hourly_means.index, y=hourly_means.values, marker='o')
plt.title('Mean Hourly Rentals by Hour of Day')
plt.xlabel('Hour')
plt.ylabel('Mean Rentals')
plt.grid(True)
plt.show()
train = pd.read_csv("train.csv", parse_dates=["datetime"])

train["year"] = train["datetime"].dt.year
train["month"] = train["datetime"].dt.month
train["hour"] = train["datetime"].dt.hour
train["weekday"] = train["datetime"].dt.day_name()

season_map = {1: "spring", 2: "summer", 3: "fall", 4: "winter"}
train["season"] = train["season"].map(season_map)
plt.figure(figsize=(14, 8))
sns.lineplot(data=train, x='hour', y='count', hue='weekday', estimator='mean', errorbar=None)
plt.title('Mean Hourly Rentals by Hour and Day of Week')
plt.xlabel('Hour')
plt.ylabel('Mean Rentals')
plt.grid(True)
plt.legend(title='Weekday')
plt.show()
g = sns.FacetGrid(train, col='season', col_wrap=2, height=5, aspect=1.5)
g.map(sns.lineplot, 'hour', 'count', estimator='mean', errorbar=None)
g.set_titles('Season: {col_name}')
g.set_axis_labels('Hour', 'Mean Rentals')
g.fig.suptitle('Mean Hourly Rentals by Hour and Season', y=1.02)
plt.show()
def create_day_period(hour):
    if 0 <= hour <= 6:
        return 'night'
    elif 6 < hour <= 12:
        return 'morning'
    elif 12 < hour <= 18:
        return 'afternoon'
    else:
        return 'evening'

train['day_period'] = train['hour'].apply(create_day_period)
period_group = train.groupby('day_period')['count']

means = period_group.mean()

# Manual 95% CI calculation
ci = period_group.apply(lambda x: stats.t.interval(0.95, len(x)-1, loc=np.mean(x), scale=stats.sem(x)))

ci_lower = pd.Series([c[0] for c in ci], index=means.index)
ci_upper = pd.Series([c[1] for c in ci], index=means.index)

# Logical order for day periods
order = ['night', 'morning', 'afternoon', 'evening']
means = means.reindex(order)
ci_lower = ci_lower.reindex(order)
ci_upper = ci_upper.reindex(order)

# Plot
plt.figure(figsize=(9, 6))
sns.barplot(x=means.index, y=means.values)
plt.errorbar(x=means.index, y=means.values,
             yerr=[means - ci_lower, ci_upper - means],
             fmt='none', capsize=5, color='black')
plt.title('Mean Hourly Rentals by Day Period (with 95% CI)')
plt.xlabel('Day Period')
plt.ylabel('Mean Rentals')
plt.show()
corr_matrix = train[numerical_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Correlation Matrix Heatmap')
plt.show()

#pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Page config
st.set_page_config(page_title="DC Bike Rentals Dashboard", layout="wide")

# Title
st.title("🚲 Washington D.C. Bike Rentals Dashboard")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("train.csv")
    df["datetime"] = pd.to_datetime(df["datetime"])
    df["year"] = df["datetime"].dt.year
    df["month"] = df["datetime"].dt.month
    df["hour"] = df["datetime"].dt.hour
    df["dayofweek"] = df["datetime"].dt.day_name()

    season_map = {1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"}
    df["season"] = df["season"].map(season_map)

    weather_map = {
        1: "Clear",
        2: "Mist/Cloudy",
        3: "Light Rain/Snow",
        4: "Heavy Rain/Snow"
    }
    df["weather"] = df["weather"].map(weather_map)

    return df

df = load_data()

# ------------------ SIDEBAR FILTERS ------------------
st.sidebar.header("🔧 Filters")

year_option = st.sidebar.selectbox(
    "Select Year",
    options=["All", 2011, 2012]
)

working_day_option = st.sidebar.selectbox(
    "Working Day",
    options=["All", "Yes", "No"]
)

season_option = st.sidebar.multiselect(
    "Select Season",
    options=df["season"].unique(),
    default=df["season"].unique()
)

# Apply filters
filtered_df = df.copy()

if year_option != "All":
    filtered_df = filtered_df[filtered_df["year"] == year_option]

if working_day_option == "Yes":
    filtered_df = filtered_df[filtered_df["workingday"] == 1]
elif working_day_option == "No":
    filtered_df = filtered_df[filtered_df["workingday"] == 0]

filtered_df = filtered_df[filtered_df["season"].isin(season_option)]

# ------------------ PLOTS ------------------

st.subheader("📊 Key Insights")

col1, col2 = st.columns(2)

# 1️⃣ Mean rentals by hour
with col1:
    st.markdown("### Mean Rentals by Hour")
    fig, ax = plt.subplots()
    sns.lineplot(
        data=filtered_df,
        x="hour",
        y="count",
        estimator="mean",
        ax=ax
    )
    ax.set_ylabel("Mean Rentals")
    st.pyplot(fig)

# 2️⃣ Mean rentals by month
with col2:
    st.markdown("### Mean Rentals by Month")
    fig, ax = plt.subplots()
    sns.barplot(
        data=filtered_df,
        x="month",
        y="count",
        estimator="mean",
        ax=ax
    )
    ax.set_ylabel("Mean Rentals")
    st.pyplot(fig)

# 3️⃣ Mean rentals by season
st.markdown("### Mean Rentals by Season")
fig, ax = plt.subplots()
sns.barplot(
    data=filtered_df,
    x="season",
    y="count",
    estimator="mean",
    ax=ax
)
ax.set_ylabel("Mean Rentals")
st.pyplot(fig)

# 4️⃣ Mean rentals by weather
st.markdown("### Mean Rentals by Weather Condition")
fig, ax = plt.subplots()
sns.barplot(
    data=filtered_df,
    x="weather",
    y="count",
    estimator="mean",
    ax=ax
)
ax.set_ylabel("Mean Rentals")
st.pyplot(fig)

# 5️⃣ Registered vs Casual
st.markdown("### Registered vs Casual Rentals")
fig, ax = plt.subplots()
filtered_df[["registered", "casual"]].mean().plot(kind="bar", ax=ax)
ax.set_ylabel("Average Rentals")
st.pyplot(fig)

# Footer
st.markdown("___")
st.markdown("📌 **Built using Streamlit | Data Visualization Assignment 3.3**")